// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgbaqi4Y-bZ3JWTgFo5PxFC_tKcgwPhc',
    appId: '1:1018648084688:web:75d394a5cd2f47eae9ded5',
    messagingSenderId: '1018648084688',
    projectId: 'alertika-4eef6',
    authDomain: 'alertika-4eef6.firebaseapp.com',
    storageBucket: 'alertika-4eef6.firebasestorage.app',
    measurementId: 'G-CR2EE5Q9SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT3IhNONXs5r9ZLdavGf_dTD65g2SScJ4',
    appId: '1:1018648084688:android:e860344568e38511e9ded5',
    messagingSenderId: '1018648084688',
    projectId: 'alertika-4eef6',
    storageBucket: 'alertika-4eef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK18-tYDZCOF4Ke_VLcE_LxVbD3dQoFyw',
    appId: '1:1018648084688:ios:1ac0db756dd957c1e9ded5',
    messagingSenderId: '1018648084688',
    projectId: 'alertika-4eef6',
    storageBucket: 'alertika-4eef6.firebasestorage.app',
    iosBundleId: 'com.example.sosa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK18-tYDZCOF4Ke_VLcE_LxVbD3dQoFyw',
    appId: '1:1018648084688:ios:1ac0db756dd957c1e9ded5',
    messagingSenderId: '1018648084688',
    projectId: 'alertika-4eef6',
    storageBucket: 'alertika-4eef6.firebasestorage.app',
    iosBundleId: 'com.example.sosa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgbaqi4Y-bZ3JWTgFo5PxFC_tKcgwPhc',
    appId: '1:1018648084688:web:76cf319fe9748d6fe9ded5',
    messagingSenderId: '1018648084688',
    projectId: 'alertika-4eef6',
    authDomain: 'alertika-4eef6.firebaseapp.com',
    storageBucket: 'alertika-4eef6.firebasestorage.app',
    measurementId: 'G-C4E4J3Y5D6',
  );
}
